# This is a basic workflow to help you get started with Actions
# TEST ACTION V.0

name: GitHub action test

# Controls when the workflow will run
on:
  # Triggers the workflow on push for testAction or pull request for the "main" branch
  push:
    branches: [ "testAction" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version:  22
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
