name: jest&eslint

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./pyschool-frontend #existen dos package.json en el repositorio
        run: npm ci

      - name: Run ESLint
        working-directory: ./pyschool-frontend 
        run: npm run lint

      - name: Run tests
        working-directory: ./pyschool-frontend
        run: npm test


