name: Monorepo releases (frontend + backend)

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '55 3 * * 1'  # semanal, c/domingo a las 23.55

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
