name: Auto Release Front

on:
  push:
    branches:
      - main

jobs:
  release_frontend:
    name: Create Frontend Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Linux: instalaci칩n con reintentos
      - name: Install jq on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          for i in 1 2 3; do
            sudo apt-get install -y jq && break || sleep 10
          done

      # Windows: instalaci칩n con reintentos
      - name: Install jq on Windows
        if: runner.os == 'Windows'
        run: |
          for /l %%i in (1,1,3) do (
            choco install jq -y && exit /b 0
            timeout /t 10
          )
          
      - name: Get version from pyschool-frontend/package.json
        id: get_front_version
        shell: bash
        run: |
          VERSION=$(jq -r .version pyschool-frontend/package.json)
          echo "FRONT_VERSION=$VERSION" >> $GITHUB_ENV

      # Crear release del frontend
      - name: Create Frontend Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: frontend-v${{ env.FRONT_VERSION }}
          name: Frontend Release v${{ env.FRONT_VERSION }}
          body: |
            Nueva versi칩n del FRONTEND generada autom치ticamente.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
